/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app/route'
import { Route as AppTodosIndexImport } from './routes/_app/todos/index'
import { Route as AppProjectIndexImport } from './routes/_app/project/index'
import { Route as AppPlaygroundIndexImport } from './routes/_app/playground/index'
import { Route as AppDashboardIndexImport } from './routes/_app/dashboard/index'
import { Route as AppAnalyticsIndexImport } from './routes/_app/analytics/index'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AppRouteRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const AppTodosIndexRoute = AppTodosIndexImport.update({
  id: '/todos/',
  path: '/todos/',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppProjectIndexRoute = AppProjectIndexImport.update({
  id: '/project/',
  path: '/project/',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppPlaygroundIndexRoute = AppPlaygroundIndexImport.update({
  id: '/playground/',
  path: '/playground/',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppDashboardIndexRoute = AppDashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppAnalyticsIndexRoute = AppAnalyticsIndexImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => AppRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_app/analytics/': {
      id: '/_app/analytics/'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsIndexImport
      parentRoute: typeof AppRouteImport
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardIndexImport
      parentRoute: typeof AppRouteImport
    }
    '/_app/playground/': {
      id: '/_app/playground/'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof AppPlaygroundIndexImport
      parentRoute: typeof AppRouteImport
    }
    '/_app/project/': {
      id: '/_app/project/'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof AppProjectIndexImport
      parentRoute: typeof AppRouteImport
    }
    '/_app/todos/': {
      id: '/_app/todos/'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof AppTodosIndexImport
      parentRoute: typeof AppRouteImport
    }
  }
}

// Create and export the route tree

interface AppRouteRouteChildren {
  AppAnalyticsIndexRoute: typeof AppAnalyticsIndexRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppPlaygroundIndexRoute: typeof AppPlaygroundIndexRoute
  AppProjectIndexRoute: typeof AppProjectIndexRoute
  AppTodosIndexRoute: typeof AppTodosIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAnalyticsIndexRoute: AppAnalyticsIndexRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppPlaygroundIndexRoute: AppPlaygroundIndexRoute,
  AppProjectIndexRoute: AppProjectIndexRoute,
  AppTodosIndexRoute: AppTodosIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/playground': typeof AppPlaygroundIndexRoute
  '/project': typeof AppProjectIndexRoute
  '/todos': typeof AppTodosIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/playground': typeof AppPlaygroundIndexRoute
  '/project': typeof AppProjectIndexRoute
  '/todos': typeof AppTodosIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/analytics/': typeof AppAnalyticsIndexRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/playground/': typeof AppPlaygroundIndexRoute
  '/_app/project/': typeof AppProjectIndexRoute
  '/_app/todos/': typeof AppTodosIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/analytics'
    | '/dashboard'
    | '/playground'
    | '/project'
    | '/todos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/login'
    | '/analytics'
    | '/dashboard'
    | '/playground'
    | '/project'
    | '/todos'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/analytics/'
    | '/_app/dashboard/'
    | '/_app/playground/'
    | '/_app/project/'
    | '/_app/todos/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app",
        "/login"
      ]
    },
    "/_app": {
      "filePath": "_app/route.tsx",
      "children": [
        "/_app/analytics/",
        "/_app/dashboard/",
        "/_app/playground/",
        "/_app/project/",
        "/_app/todos/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_app/analytics/": {
      "filePath": "_app/analytics/index.tsx",
      "parent": "/_app"
    },
    "/_app/dashboard/": {
      "filePath": "_app/dashboard/index.tsx",
      "parent": "/_app"
    },
    "/_app/playground/": {
      "filePath": "_app/playground/index.tsx",
      "parent": "/_app"
    },
    "/_app/project/": {
      "filePath": "_app/project/index.tsx",
      "parent": "/_app"
    },
    "/_app/todos/": {
      "filePath": "_app/todos/index.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
